apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: carts-deploy-task
spec:
  params:
  - name: name-space
    description: name to namespace for depolyment
  workspaces:
  - name: source
  # Step to create Knative Service from YAML file using kubectl.
  steps:
    - name: debug
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        pwd
        ls -gAhF
        echo "-----------"
        ls -gAhf source/
    
    - name: apply-database
      image: "bitnami/kubectl"
      command: ["kubectl"]
      args: ["apply", "-f", "source/tekton/test-deploy/carts-db-dep.yaml","-f","source/tekton/test-deploy/carts-db-svc.yaml","-n","$(params.name-space)"]

    - name: kubectl
      image: "bitnami/kubectl"
      command: ["apply"]
      args: ["create", "-f", "source/tekton/test-deploy/carts-dep.yaml","-f","source/tekton/test-deploy/carts-svc.yaml","-n","$(params.name-space)"]
