apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fe-deploy-task
spec:
  params:
  - name: name-space
    description: name to namespace for depolyment
  workspaces:
  - name: source
  # Step to create Knative Service from YAML file using kubectl.
  steps:
    - name: kubectl
      workingDir: $(workspaces.source)
      image: "bitnami/kubectl"
      command: ["kubectl"]
      args: ["create", "-f", "tekton/test-deploy/front-end-dep.yaml","-f","tekton/test-deploy/front-end-svc.yaml","-n","$(params.name-space)"]
