apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fe-deploy-task
spec:
  # Step to create Knative Service from YAML file using kubectl.
  steps:
    - name: kubectl
      image: "bitnami/kubectl"
      command: ["kubectl"]
      args: ["create", "-f", "https://github.com/alh-alabdullatif/level3-project-alhanouf/blob/develop/tekton/test-deploy/orders-dep.yaml","-f","https://github.com/alh-alabdullatif/level3-project-alhanouf/blob/develop/tekton/test-deploy/orders-svc.yaml","-f","https://github.com/alh-alabdullatif/level3-project-alhanouf/blob/develop/tekton/test-deploy/orders-db-dep.yaml","-f","https://github.com/alh-alabdullatif/level3-project-alhanouf/blob/develop/tekton/test-deploy/orders-db-svc.yaml","-n","prod"]
