apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
spec:
  selector:
    matchLabels:
      name: catalogue
  replicas: 1
  template:
    metadata:
      labels:
        name: catalogue
    spec:
      containers:
      - name: catalogue
        image: alhanouf1/catalogue-build
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
