apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    name: payment
spec:
  selector:
    matchLabels:
      name: payment
  replicas: 1
  template:
    metadata:
      labels:
        name: payment
    spec:
      containers:
      - name: payment
        image: alhanouf1/payment-build
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
