apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-master
  labels:
    name: queue-master
spec:
  selector:
    matchLabels:
      name: queue-master
  replicas: 1
  template:
    metadata:
      labels:
        name: queue-master
    spec:
      containers:
      - name: queue-master
        image: alhanouf1/q-master-build
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
