# syntax=docker/dockerfile:experimental
FROM maven:3-jdk-8 AS build 

#WORKDIR /usr/src/app
#COPY *.jar ./app.jar

WORKDIR /tmp-q
COPY src /tmp-q/src 
COPY pom.xml /tmp-q

RUN mvn clean package


#ENTRYPOINT ["/usr/local/bin/java.sh","-jar","./app.jar", "--port=80"]
FROM weaveworksdemos/msd-java:jre-latest

#FROM java:openjdk-8-alpine

COPY --from=build /tmp-q/target/queue-master.jar /queue-master.jar

ENV	SERVICE_USER=myuser \
	SERVICE_UID=10001 \
	SERVICE_GROUP=mygroup \
	SERVICE_GID=10001

RUN	addgroup -g ${SERVICE_GID} ${SERVICE_GROUP} && \
	adduser -g "${SERVICE_NAME} user" -D -H -G ${SERVICE_GROUP} -s /sbin/nologin -u ${SERVICE_UID} ${SERVICE_USER} && \
	apk add --update libcap && \
	mkdir /lib64 && \
	ln -s /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server/libjvm.so /lib/libjvm.so && \
	ln -s /usr/lib/jvm/java-1.8-openjdk/lib/amd64/jli/libjli.so /lib/libjli.so && \
	setcap 'cap_net_bind_service=+ep' $(readlink -f $(which java))

#WORKDIR /usr/src/app
#COPY *.jar ./app.jar

RUN	chown -R ${SERVICE_USER}:${SERVICE_GROUP} ../queue-master.jar

USER ${SERVICE_USER}

ENTRYPOINT ["/usr/local/bin/java.sh","-jar","./app.jar", "--port=80"]

#ENTRYPOINT ["java","-Djava.security.egd=file:/dev/urandom","-jar","../queue-master.jar", "--port=80"]
